const mockEvents = {
    city: {
        id: 1007700,
        city: 'München',
        lat: 48.14,
        lon: 11.58,
        state: '',
        country: 'de',
        zip: 'meetup3',
        member_count: 1257,
    },
    events: [
        {
            created: 1557483479000,
            duration: 46800000,
            id: '261346344',
            name: 'Easy Hike : Breitachklamm [13.8km, 350m gain]',
            rsvp_limit: 20,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561005900000,
            local_date: '2019-06-20',
            local_time: '06:45',
            rsvp_close_offset: 'PT18H45M',
            updated: 1558600416000,
            utc_offset: 7200000,
            waitlist_count: 60,
            yes_rsvp_count: 20,
            venue: {
                id: 26183168,
                name: 'Munich Hauptbahnhof (Main Station)',
                lat: 48.14141845703125,
                lon: 11.557615280151367,
                repinned: true,
                address_1: 'Arnulfstraße 15',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1389721197000,
                name: 'Hiking near Munich',
                id: 12113182,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Hiking-near-Munich',
                who: 'Munich hikers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Hiking-near-Munich/events/261346344/',
            description: '<p>Hey y´all</p> <p>Another easy and relaxed one.</p> <p>Hoping the weather will be okay - I would love to go with you! </p> ',
            how_to_find_us: 'Shop at Platforms 27-36',
            visibility: 'public',
        },
        {
            local_time: '19:00',
            local_date: '2019-06-13',
            link: 'https://www.meetup.com/rice-cookie-improv/events/flrdzqyzjbrb/',
            visibility: 'public_limited',
            group: {
                created: 1468649601000,
                name: 'Rice Cookie Improvtheater in Munich',
                id: 20189476,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'rice-cookie-improv',
                who: 'Improv-Enthusiasts',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            waitlist_count: 3,
            yes_rsvp_count: 10,
            duration: 7200000,
            time: 1560445200000,
            utc_offset: 7200000,
            name: 'Workshop: Get loose with Improv Theater',
            id: 'flrdzqyzjbrb',
        },
        {
            created: 1558336922000,
            duration: 39600000,
            id: '261608978',
            name: 'Longer Hike: Starnberg - Maisinger See - Herrsching [19km; 230m gain]',
            rsvp_limit: 25,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1562996700000,
            local_date: '2019-07-13',
            local_time: '07:45',
            rsvp_close_offset: 'PT19H45M',
            updated: 1558508997000,
            utc_offset: 7200000,
            waitlist_count: 53,
            yes_rsvp_count: 25,
            venue: {
                id: 26183168,
                name: 'Munich Hauptbahnhof (Main Station)',
                lat: 48.14128875732422,
                lon: 11.559012413024902,
                repinned: true,
                address_1: 'Arnulfstraße 15',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1389721197000,
                name: 'Hiking near Munich',
                id: 12113182,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Hiking-near-Munich',
                who: 'Munich hikers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Hiking-near-Munich/events/261608978/',
            description: '<p>Hey y´all</p> <p>For everyone who is not joining on 30th May or wanting something a little longer: Here we go :)</p> <p>Hoping the weather will be okay - I would love to go to one of my most loved places with you!</p> <p>We would meet at 07:45am at the Central Station; in front of the lower Starbucks (North Entrance of Main Hall, take staircase to mid-level just before you head to S-Bahn level)</p> <p>The tour itself is at 19km, 270m gain. It should take around 6-7 hours, depending on how relaxed we take it and how long we stay at the Biergarten for lunch. You can either take something to eat with you and buy something. We might also be able to have an early dinner at Kloster Andechs.</p> <p>Tipp:<br/>Take swimming gear with you, if you feel like taking a dive into the water :)</p> <p>Train Journey Details:<br/>Departure 08.32 Uhr / S6 to Starnberg, Exit at Starnberg<br/>Return / S8 from Herrsching</p> <p>Ticket Information:<br/>Please make sure to have proper MVG Tickets. We will have the opportunity to buy group-day-tickets when meeting; depending on the number of people joining.</p> <p>What is important:</p> <p>- Trekking Shoes to be recommended<br/>- enough water and snacks for along the way<br/>- swimming gear :)</p> <p>Kindly note that end of RSVP is on Friday, 12th July at 12pm. Anyone changing the status afterwards to no without a short email to me or anyone just not showing up will be marked as no show as a reference for future smaller hikes.</p> ',
            visibility: 'public',
        },
        {
            created: 1548414814000,
            duration: 957600000,
            id: '258384273',
            name: 'Lechtalweg - Lech Route',
            rsvp_limit: 22,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1566979200000,
            local_date: '2019-08-28',
            local_time: '10:00',
            updated: 1559492619000,
            utc_offset: 7200000,
            waitlist_count: 1,
            yes_rsvp_count: 22,
            venue: {
                id: 26044376,
                name: 'Munich Central Station',
                lat: 48.14026641845703,
                lon: 11.55999755859375,
                repinned: true,
                address_1: 'Bayerstraße 10A',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1389721197000,
                name: 'Hiking near Munich',
                id: 12113182,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Hiking-near-Munich',
                who: 'Munich hikers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Hiking-near-Munich/events/258384273/',
            description: '<p>[UPDATE]<br/>Let´s meet on Wednesday, 8th May at 06.30pm to talk routes, arrangements, etc. I would send out an email with the location prior to this day.</p> <p>[INFORMATION]<br/>I am currently in the process of booking my accomodation. For everyone who is fairly certain that he/she would like to join. Feel free to send me an email and I will let you know where to book.</p> <p>The Lechweg offers an extraordinary nature experience; it accompanies the Lech for almost 125km. From its spring near the Formarinsee in the Austrian Alps to the Lechfall in Füssen, Germany.</p> <p>This is one of my challenges for 2019 and I would love to have some company! Are you up for it? :)</p> <p>This MeetUp is functioning as framework as I really would love the idea of getting to know you beforehand and even plan together. The below route is just an idea and can be changed to whatever suits us best.</p> <p>I would suggest for a meetup in a coffee shop - maybe around March - to discuss details and routes and locations to stay overnight.</p> <p>I am actually already really excited. Although I am suffering an injured ankle at the moment :) :) :) Looking forward to meeting you all!</p> <p>Current Route:<br/>Day 1/Wednesday 28th August<br/>Journey to Innerbraz (to be reached by train from Munich via Bludenz)</p> <p>Day 2/Thursday, 29th August - Mountain Day<br/>Innerbraz to Freibürger Hütte (Formarinsee) - 13km - 1´2300m elevation with overnight stay - Very good fitness required. Mostly accessible paths. Sure-footedness required.</p> <p>Day 3/Friday, 30th August - Lech Day<br/>Freibürger Hütte to Lech - 14km - 650m elevation - easy hike<br/>Overnight Stay in Lech am Arlberg</p> <p>Day 4/Saturday, 31st August - Mountain Day<br/>Lech am Arlberg to Stuttgarter Hütte - 10km - 1´100m elevation, uphill - Sure-footedness, sturdy shoes and alpine experience required</p> <p>Day 5/Sunday, 1st September- Mountain Day<br/>Stuttgarter Hütte to Steeg - 14km - 1240m elevation, downhill - Good fitness required. Mostly accessible paths. Sure-footedness required</p> <p>Day 6/Monday, 2nd September - Lech Day<br/>Steeg via Holzgau to Elbigenalp - 15km - 200m elevation along the river</p> <p>Day 7/ Tuesday, 3rd September - Lech Day<br/>Elbigenalp to Vorderhornbach - 17km - 400m elevation along the river</p> <p>Day 8/ Wednesday, 4th September - Lech Day<br/>Vorderhornbach to Weißenbach - 14,5km - 100m elevation along the river</p> <p>Day 9/Thursday, 5th September - Lech Day<br/>Weißenbach to Pflach - 14km - 100m elevation partly along the river and via panorama trail</p> <p>Day 10/ Friday, 6th September - Lech Day<br/>Pflach to Füssen via Alpsee and View to Neuschwanstein - 13km - 400m elevation</p> <p>Day 11/ Saturday, 7th September<br/>Journey back home</p> <p>Obviously I am not a trained tour leader of any kind. So participation is on your own responsibility. Each of us will be responsible for their own bookings in regards to train tickets, overnight stays etc.</p> ',
            visibility: 'public',
        },
        {
            local_time: '15:00',
            local_date: '2019-06-15',
            link: 'https://www.meetup.com/rice-cookie-improv/events/jlrdzqyzjbtb/',
            visibility: 'public_limited',
            group: {
                created: 1468649601000,
                name: 'Rice Cookie Improvtheater in Munich',
                id: 20189476,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'rice-cookie-improv',
                who: 'Improv-Enthusiasts',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            waitlist_count: 0,
            yes_rsvp_count: 9,
            duration: 10800000,
            time: 1560603600000,
            utc_offset: 7200000,
            name: 'Workshop: Get loose with Improv Theater',
            id: 'jlrdzqyzjbtb',
        },
        {
            created: 1559922617000,
            duration: 7200000,
            id: '262127908',
            name: 'Weekly Eye Contact',
            rsvp_limit: 100,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1560531600000,
            local_date: '2019-06-14',
            local_time: '19:00',
            updated: 1559922644000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 26,
            venue: {
                id: 25392191,
                name: 'Cafe Luitpold ',
                lat: 48.14292907714844,
                lon: 11.575007438659668,
                repinned: true,
                address_1: 'Brienner Straße 11 ',
                address_2: '80333 München ',
                city: 'München ',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1455135194000,
                name: 'Eye Contact Munich',
                id: 19551209,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'eye-contact-munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/eye-contact-munich/events/262127908/',
            description: '<p>Hi All,</p> <p>bald ist es wieder soweit: ein großes Eye Contact Event!</p> <p>Eye-Contact bedeutet, Du setzt Dich gegenüber einer Person, die Du oft nicht mal kennst und blickst ihr einfach in die Augen, das ist alles. Einen Eindruck vom Experiment gewinnst du in diesem Video:<br/><a href=\'https://www.youtube.com/watch?v=1EumnijQBhw&amp;t=4s\' class=\'embedded\'>https://www.youtube.com/watch?v=1EumnijQBhw&amp;t=4s</a></p> <p>Bei diesen Events kommen Menschen jeglichen Alters, jeglicher Nation oder Glaubens zusammen und schauen sich einfach in die Augen. Aus Fremden werden Freund*innen, jede*r erlebt ganz unterschiedliche Dinge. Aber eines sagen die Teilnehmenden immer wieder: es ist wunderbar, zu erleben, wie einfach man sich mit Menschen verbinden kann!</p> <p>Neugierig geworden?</p> <p>Wir treffen uns am 14. Juni im Cafe Luitpold. Von 19.00 bis 21.00 Uhr werdet Ihr die Gelegenheit haben, Eure eigenen Erfahrungen zu machen.</p> <p>Wir freuen uns darauf Dich zu sehen. Bring auch gern Freund*innen mit.</p> <p>Eye Contact Munich</p> <p>Brienner Str. 11<br/>80333 München<br/>Eintritt: 4 EUR</p> ',
            visibility: 'public',
        },
        {
            created: 1558509204000,
            duration: 7200000,
            id: 'thdxzqyzjbvb',
            name: 'Let\'s Play Kickball!',
            rsvp_limit: 20,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1560682800000,
            local_date: '2019-06-16',
            local_time: '13:00',
            rsvp_close_offset: 'PT2H',
            updated: 1558509204000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 19,
            venue: {
                id: 26293604,
                name: 'Chinese Tower',
                lat: 48.15256118774414,
                lon: 11.59210205078125,
                repinned: false,
                address_1: 'Englischer Garten 3',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1469016785000,
                name: 'Munich Kickball',
                id: 20204783,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-Kickball',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munchen-Kickball/events/thdxzqyzjbvb/',
            description: '<p>Hey neuer oder routinierter Kickball Player ;)</p> <p>Wir warten auf dich wie üblich um 13 Uhr an der südwestlichen Ecke des chinesischen Turms. Wir sind diejenigen mit dem roten Kickball-Ball:</p> <p>goo.gl/maps/Pqp9ecnv3Xx</p> <p>Wenn du ein bisschen später auftauchen kannst, komm einfach spontan auf das Fels. Es liegt etwas nördlich vom Chinesischen Turm:<br/>goo.gl/maps/DQjErwppk8z</p> <p>Fühl dich frei deine Freunde mitzubringen! Zusätzliche Spieler und neue Gesichter sind immer willkommen. Essen und Getränke kannst du gern mitbringen.</p> <p>Wir freuen uns, dich am Sonntag zu sehen!</p> <p>----------------------------</p> <p>Hey Gang!</p> <p>Feel free to bring blankets, drinks, and food if you like. Also feel free to bring friends! Extra players and new faces are always welcome.</p> <p>Meet at the Chinese Tower at 1 pm, southwest corner. We\'ll be the weirdos carrying the big red kickballs:</p> <p><a href=\'https://goo.gl/maps/Pqp9ecnv3Xx\' class=\'linkified\'>https://goo.gl/maps/Pqp9ecnv3Xx</a></p> <p>If you show up a bit late you can meet us at the field, which is a bit north of the Chinese Tower:</p> <p><a href=\'https://goo.gl/maps/DQjErwppk8z\' class=\'linkified\'>https://goo.gl/maps/DQjErwppk8z</a></p> <p>Looking forward to seeing you all on Sunday!</p> <p>- Scott</p> ',
            visibility: 'public',
        },
        {
            created: 1559417984000,
            duration: 18000000,
            id: '261960976',
            name: 'Candlelight tales along the Isar',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561136400000,
            local_date: '2019-06-21',
            local_time: '19:00',
            rsvp_close_offset: 'PT144H',
            updated: 1559417984000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 15,
            venue: {
                id: 26223377,
                name: 'Gasthaus Alter Wirt',
                lat: 48.10050582885742,
                lon: 11.545145034790039,
                repinned: false,
                address_1: 'Fraunbergstraße 8',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1423920004000,
                name: 'Munich Explorers Club',
                id: 18434240,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Explorers-Club',
                who: 'Explorers',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munich-Explorers-Club/events/261960976/',
            description: '<p>Dear all,</p> <p>It is with great pleasure that I come back to Munich to visit for a few days after a trip to the Faroe Islands!</p> <p>It would be great to see some old faces and new from the Munich Explorers Club. Let\'s plan an informal (and perhaps unusual) get-together for Friday, June 21, starting with dinner at the Gasthaus Alter Wirt in Thalkirchen. From there we can walk down to the Isar and stake out a spot along the riverbank just before dark. Bring your favorite personal travel or adventure story to tell, and we will take turns passing the candle (or flashlight). Feel free to bring blankets, drinks, etc.</p> <p>Hope to see you there!</p> <p>Steve</p> ',
            visibility: 'public',
        },
        {
            created: 1557561821000,
            duration: 7200000,
            id: 'hggczqyzjbmc',
            name: 'Come run with the MH3!',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561820400000,
            local_date: '2019-06-29',
            local_time: '17:00',
            updated: 1557561821000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 2,
            group: {
                created: 1436202691000,
                name: 'Munich Hash House Harriers',
                id: 18722783,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Hash-House-Harriers',
                who: 'Hashers and Harriettes',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/hggczqyzjbmc/',
            description: '<p>A trail is set by a \'hare\' usually in flour and/or chalk and then the \'pack\' has to try and find \'true trail\' at junctions. It is like a treasure hunt/ Schnitzel Lauf. The trails are therefore ideal for all levels of running with faster runners able to run more to check out the correct way and slower runners given the opportunity to catch up. We are not a road running group and our trails often take us into the forests or even off trail completely. It is a good way to get into fun running as it tends to be quite stop and go, rather than a continuous run.</p> <p>We are now on summer time. Don\'t forget to bring mozzie spray for the circle. There will be cars to store your bags.</p> <p>We\'ll post info here as it becomes available for the next run.</p> <p>You can also go to our regular website at <a href=\'http://www.munich-h3.eu \' class=\'linkified\'>http://www.munich-h3.eu</a></p> <p>or subscribe to the mailing list at [masked]</p> <p>We promise not to spam you. :-)</p> ',
            how_to_find_us: 'To be decided',
            visibility: 'public',
        },
        {
            created: 1557561821000,
            duration: 7200000,
            id: 'hggczqyzkbrb',
            name: 'Come run with the MH3!',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1563030000000,
            local_date: '2019-07-13',
            local_time: '17:00',
            updated: 1557561821000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 2,
            group: {
                created: 1436202691000,
                name: 'Munich Hash House Harriers',
                id: 18722783,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Hash-House-Harriers',
                who: 'Hashers and Harriettes',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/hggczqyzkbrb/',
            description: '<p>A trail is set by a \'hare\' usually in flour and/or chalk and then the \'pack\' has to try and find \'true trail\' at junctions. It is like a treasure hunt/ Schnitzel Lauf. The trails are therefore ideal for all levels of running with faster runners able to run more to check out the correct way and slower runners given the opportunity to catch up. We are not a road running group and our trails often take us into the forests or even off trail completely. It is a good way to get into fun running as it tends to be quite stop and go, rather than a continuous run.</p> <p>We are now on summer time. Don\'t forget to bring mozzie spray for the circle. There will be cars to store your bags.</p> <p>We\'ll post info here as it becomes available for the next run.</p> <p>You can also go to our regular website at <a href=\'http://www.munich-h3.eu \' class=\'linkified\'>http://www.munich-h3.eu</a></p> <p>or subscribe to the mailing list at [masked]</p> <p>We promise not to spam you. :-)</p> ',
            how_to_find_us: 'To be decided',
            visibility: 'public',
        },
        {
            created: 1559597772000,
            duration: 9000000,
            id: '262016793',
            name: 'Photo outing - Munich street scences',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1560587400000,
            local_date: '2019-06-15',
            local_time: '10:30',
            updated: 1559597791000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 28,
            venue: {
                id: 26244972,
                name: 'Fish\'s Fountain',
                lat: 48.137245178222656,
                lon: 11.576180458068848,
                repinned: false,
                address_1: 'Marienplatz',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1500930561000,
                name: 'Photography Workshops Munich',
                id: 25119735,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-Photography-Workshops',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munchen-Photography-Workshops/events/262016793/',
            description: '<p>Let\'s take photos of Munich\'s busy streets!</p> <p>We can share our thoughts about street-photography and practice a little taking photos of strangers in small groups.</p> <p>At the beginning, we will visit some touristic places such as the Viktualienmarkt, where people are used to being photographed. Once we have build up a little momentum and confidence in taking pictures of people on the street, we can venture to Karlsplatz and the Hauptbahnhof area to observe the different faces of Munich downtown!</p> <p>We will end at a cafe/restaurant and have a nice chat afterwards :)</p> ',
            how_to_find_us: 'By the fountain at Marienplatz',
            visibility: 'public',
        },
        {
            created: 1559561039000,
            duration: 10800000,
            id: '261999193',
            name: 'Make new friends! (21 to 45) - Meet ladies and gentlemen (Free Drink/Hosted)',
            rsvp_limit: 90,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1560528000000,
            local_date: '2019-06-14',
            local_time: '18:00',
            updated: 1559561039000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 70,
            venue: {
                id: 26202035,
                name: '1912 Restaurant & Bar',
                lat: 48.137569427490234,
                lon: 11.559064865112305,
                repinned: false,
                address_1: 'Schwanthalerstraße 36',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1465921965000,
                name: 'The Expats Club of Munich (GERMANS welcome!) (2300+ expats)',
                id: 20073299,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Expat-and-Internationals-Meetup',
                who: 'Internationals',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munich-Expat-and-Internationals-Meetup/events/261999193/',
            description: '<p>Please come and join us for a wonderful evening of making new friends with like minded ladies and gentlemen at the fabulous 1912 Restaurant &amp; Bar. You will be welcomed by your host Lydia and also be introduced to some of the other attendees. All our members also get exclusive FREE welcome drink. Join us and get started on making new connections and friendships!</p> <p>Our last social we had over 50 members present and this time wont be no different!</p> <p>Please click on the link below to purchase your ticket:<br/><a href=\'https://munich21to45.eventbrite.co.uk \'class=linkified>https://munich21to45.eventbrite.co.uk</a></p> <p>Have a look at photos from our recent meetups and see what you have been missing! <a href=\'http://bit.ly/MeetupPictures\' class=\'linkified\'>http://bit.ly/MeetupPictures</a></p> <p>Some Important Points:-</p> <p>- Our area is booked for MEETUP/LYDIA</p> <p>- This meetup is for members between the ages of 21 to 45 who want to make new friends in a safe and comfortable environment. Please come early to chat with members. You have no excuse to miss this event..!</p> <p>- FREE welcome drink for all our members!</p> <p>- Your host for the evening is LYDIA who will not only welcome you to our reserved area but also help you mix and mingle. No more nervousness, no awkward silences, no fiddling with your phone or staring into glasses. You will find yourself saying more hellos, shaking more hands and making more friends. Please come early as it is far easier to meet new people then. Please request LYDIA for help with introductions.</p> <p>-Please be aware that about 95% of those who attend come alone and about 75% are attending for the first time. You will not be alone. We know how you may feel and so LYDIA will take care of you.</p> <p>-Everyone attends these events to meet other members and so there is no reason to be shy or bashful. Also be aware that most people come alone. LYDIA is there to look after you and make you comfortable.</p> <p>-Please be aware that we are not a dating group. Our events are not organised to help your dating life or to make romantic matches. Our group is created to help ladies and gents meet other like minded ladies and gents and make new friends. This could be for singles or for those who are not single. Please do not attend our event if a perfect gender balance is important for your enjoyment of our meet-up</p> <p>------------------------------</p> <p>Event cost:</p> <p>Early Bird tickets - € 5 each<br/>Regular tickets - € 10 each<br/>(If you do not purchase tickets in advance but want to come then please show up on the day and give € 15 cash to LYDIA when you meet her)</p> <p>Please click on the link below to purchase your ticket:<br/><a href=\'https://munich21to45.eventbrite.co.uk\' class=\'linkified\'>https://munich21to45.eventbrite.co.uk</a></p> <p>------------------------<br/>This meetup is organised with www.connectwithlocals.com. Please watch the video below to see why you should attend our meetups.</p> <p><a href=\'http://bit.ly/whyattendoursocials \' class=linkified>http://bit.ly/whyattendoursocials</a></p> ',
            how_to_find_us: 'Area reserved for Meetup/ LYDIA',
            visibility: 'public',
            pro_is_email_shared: false,
        },
        {
            created: 1559634750000,
            duration: 10800000,
            id: '262027604',
            name: 'Bank Holiday Party!(35 to 60) - Meet ladies and gentlemen (Free Drink/Hosted)',
            rsvp_limit: 70,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1560960000000,
            local_date: '2019-06-19',
            local_time: '18:00',
            updated: 1559634750000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 34,
            venue: {
                id: 26202035,
                name: '1912 Restaurant & Bar',
                lat: 48.137569427490234,
                lon: 11.559064865112305,
                repinned: false,
                address_1: 'Schwanthalerstraße 36',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1465921965000,
                name: 'The Expats Club of Munich (GERMANS welcome!) (2300+ expats)',
                id: 20073299,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Expat-and-Internationals-Meetup',
                who: 'Internationals',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munich-Expat-and-Internationals-Meetup/events/262027604/',
            description: '<p>If you do not have time to meet new friends over the week because your hectic work schedule, then we have the perfect social for you over an Bank Holiday!</p> <p>Please come and join us for a wonderful evening of making new friends with like minded ladies and gentlemen on a Bank Holiday at the fabulous 1912 Restaurant &amp; Bar. You will be welcomed by your host Lydia and also be introduced to some of the other attendees. All our members also get exclusive FREE welcome drink. Join us and get started on making new connections and friendships!</p> <p>Our last social we had over 40 members present and this time wont be no different!</p> <p>Please click on the link below to purchase your ticket:<br/><a href=\'https://bankholidaymunich.eventbrite.co.uk\' class=\'linkified\'>https://bankholidaymunich.eventbrite.co.uk</a></p> <p>Have a look at photos from our recent meetups and see what you have been missing! <a href=\'http://bit.ly/MeetupPictures\' class=\'linkified\'>http://bit.ly/MeetupPictures</a></p> <p>Some Important Points:-</p> <p>- Our area is booked for MEETUP/LYDIA</p> <p>- This meetup is for members between the ages of 35 to 60 who want to make new friends in a safe and comfortable environment. Please come early to chat with members. You have no excuse to miss this event..!</p> <p>- FREE welcome drink for all our members!</p> <p>- Your host for the evening is LYDIA who will not only welcome you to our reserved area but also help you mix and mingle. No more nervousness, no awkward silences, no fiddling with your phone or staring into glasses. You will find yourself saying more hellos, shaking more hands and making more friends. Please come early as it is far easier to meet new people then. Please request LYDIA for help with introductions.</p> <p>-Please be aware that about 95% of those who attend come alone and about 75% are attending for the first time. You will not be alone. We know how you may feel and so LYDIA will take care of you.</p> <p>-Everyone attends these events to meet other members and so there is no reason to be shy or bashful. Also be aware that most people come alone. LYDIA is there to look after you and make you comfortable.</p> <p>-Please be aware that we are not a dating group. Our events are not organised to help your dating life or to make romantic matches. Our group is created to help ladies and gents meet other like minded ladies and gents and make new friends. This could be for singles or for those who are not single. Please do not attend our event if a perfect gender balance is important for your enjoyment of our meet-up</p> <p>------------------------------</p> <p>Event cost:</p> <p>Early Bird tickets - € 5 each<br/>Regular tickets - € 10 each<br/>(If you do not purchase tickets in advance but want to come then please show up on the day and give € 15 cash to LYDIA when you meet her)</p> <p>Please click on the link below to purchase your ticket:<br/><a href=h\'ttps://bankholidaymunich.eventbrite.co.uk\' class=\'linkified\'>https://bankholidaymunich.eventbrite.co.uk</a></p> <p>------------------------<br/>This meetup is organised with www.connectwithlocals.com. Please watch the video below to see why you should attend our meetups.</p> <p><a href=\'http://bit.ly/whyattendoursocials\' class=\'linkified\'>http://bit.ly/whyattendoursocials</a></p> ',
            how_to_find_us: 'Area reserved for Meetup/ LYDIA',
            visibility: 'public',
            pro_is_email_shared: false,
        },
        {
            created: 1556734128000,
            duration: 130500000,
            id: '261079103',
            name: 'Overnight Hike - Soiernumrundung: Schöttelkarspitze and Soiernspitze',
            rsvp_limit: 10,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561182300000,
            local_date: '2019-06-22',
            local_time: '07:45',
            updated: 1559895497000,
            utc_offset: 7200000,
            waitlist_count: 20,
            yes_rsvp_count: 9,
            venue: {
                id: 24847646,
                name: 'Hauptbahnhof',
                lat: 48.14134216308594,
                lon: 11.557599067687988,
                repinned: true,
                address_1: 'Hauptbahnhof',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1524419703000,
                name: 'Munich International Hiking',
                id: 28247630,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-International-Hiking',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munich-International-Hiking/events/261079103/',
            description: '<p>Soiernhaus is our destination in June. We will hike up two of Karwendel\'s most famous peaks: Schöttelkarspitze and Soiernspitze. Both days require previous hiking experience, a head for heights, and proper hiking boots. Strictly no trainers or mid-height footwear. I\'m kindly asking First Timers to join at least two medium to difficult day hikes before coming on this overnight hike. Thank you.</p> <p>ROUTE</p> <p>Day 1 - Saturday 22/06/2019<br/>Krün (850m) - Schwarzkopf (1150m) - Seinskopf (1961m) - Schöttelkarspitze (2050m) - Soiernhaus and Soiernsee (1600m). Walking time = ~5h, distance = 11km, elevation gain = 1250hm. This is a medium hike. Please bring a packed lunch along.</p> <p>A sheet sleeper is required to spend the night at Soiernhaus. I booked 10x Matratzenlager for us.</p> <p>Day 2 - Sunday 23/06/2019<br/>Soiernhaus (1600m) - Schöttelkarspitze (2050m) – Reißende Lahnspitze (2170m) – Soiernspitze (2253m) - Soiernhaus (1600m) - Fischbachalm (1400m) - Krün (850m). Walking time = ~8h, distance = 19km, elevation gain = 900hm. This is a difficult hike. We will have lunch at Soiernhaus before we hike back to Krün.</p> <p>COST ESTIMATE</p> <p>- €20 night at Soiernhaus (€10 for DAV members)<br/>- €30 share of train and bus ticket (price of the train ticket will be split evenly between the group)<br/>- A deposit of €20 (€10 for DAV members) is required to secure your spot<br/>- I\'d strongly recommend to bring ~€100 of cash along to pay for your lunch, dinner, and breakfast</p> <p>Please transfer the deposit by Friday 07/06/2019 to secure your spot. You can pay by PayPal or bank transfer (please send me a PM). Please select “private” when paying by PayPal otherwise I’ll be charged a fee of €1.50.</p> <p><a href=\'http://paypal.me/sarahdheldt\' class=\'linkified\'>http://paypal.me/sarahdheldt</a></p> <p>The organiser has to pay a deposit for all ten beds when booking. Most mountain huts don\'t offer a refund if the booking is cancelled less than a week before the booking. Therefore your deposit is not refundable, either.</p> <p>MEETING POINT</p> <p>München Hbf, next to Radius Tours, 07:45am on Saturday 22.June.2018, our train leaves at 07:59.<br/>Return to Munich: Sunday 23.June.2019 ~ 8pm-ish</p> <p>--<br/><a href=\'http://www.sektion-hochland.de/soiernhaus/index.php?id=soiernhaus\' class=\'linkified\'>http://www.sektion-hochland.de/soiernhaus/index.php?id=soiernhaus</a></p> ',
            how_to_find_us: 'Next to Radius Tours',
            visibility: 'public',
        },
        {
            created: 1559143189000,
            duration: 7200000,
            id: '261866107',
            name: 'Happiness Club ',
            rsvp_limit: 15,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561190400000,
            local_date: '2019-06-22',
            local_time: '10:00',
            updated: 1559143189000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 10,
            venue: {
                id: 26065554,
                name: 'Café Katzentempel',
                lat: 48.14914321899414,
                lon: 11.575069427490234,
                repinned: true,
                address_1: 'Türkenstraße 29',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1454229357000,
                name: 'München Women\'s Sport, Well-being and Happiness',
                id: 19472511,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-Womens-Sport-Well-being-and-Happiness',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munchen-Womens-Sport-Well-being-and-Happiness/events/261866107/',
            description: '<p>Join me, the cats and other like minded women for brunch and discussion on this month\'s topic related to happiness.</p> <p>Following on from May\'s topic of RESILIENCE and the ability to bounce back when life is difficult, we will discuss SELF COMPASSION and being kinder to ourselves.</p> <p>The event is in ENGLISH and is FREE but please support the Cat Cafe by purchasing food and drinks. Thank you.</p> ',
            how_to_find_us: 'Table booked under Julie/Happiness Club',
            visibility: 'public',
        },
        {
            created: 1557840085000,
            duration: 5400000,
            id: '261449343',
            name: 'Fotowalk vom Hofgarten in den Englischen Garten',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561566600000,
            local_date: '2019-06-26',
            local_time: '18:30',
            updated: 1557840195000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 26,
            venue: {
                id: 26382269,
                name: 'Hofgarten',
                lat: 48.14277648925781,
                lon: 11.579999923706055,
                repinned: false,
                address_1: 'Hofgartenstraße 1',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany',
            },
            group: {
                created: 1517292755000,
                name: 'Smartphone-Fotografie in München',
                id: 27321953,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Smartphone-Fotografie-in-Munchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Smartphone-Fotografie-in-Munchen/events/261449343/',
            description: '<p>Beim letzten Fotowalk haben wir beschlossen, uns das nächste Mal im Hofgarten zu treffen.</p> <p>Wir treffen uns am Pavillion im Hofgarten um 18:30 Uhr, fotografieren dann dort ein bisschen und laufen dann bis zum Chinesischen Turm im Englischen Garten. Ende Juni ist hoffentlich so gutes Wetter, dass wir dort noch zusammen im Biergarten sitzen können.</p> <p>Wie immer geht es uns beim Fotowalk um den Austausch, das gemeinsame Fotografieren, das Entdecken von tollen Motiven in der Gruppe.</p> <p>Wir freuen uns auf einen schönen Walk,<br/>Simone und Mona</p> ',
            visibility: 'public',
        },
        {
            created: 1558984782000,
            duration: 25200000,
            id: '261811924',
            name: 'Infostand Promenadenfest',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1561809600000,
            local_date: '2019-06-29',
            local_time: '14:00',
            updated: 1558984782000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            group: {
                created: 1553170999000,
                name: 'München Riemer Park run',
                id: 31442178,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-Riemer-Park-run',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin',
            },
            link: 'https://www.meetup.com/Munchen-Riemer-Park-run/events/261811924/',
            description: '<p>Hallo Leute,</p> <p>Wir möchten den Münchnen Riemer Park parkrun auf dem Promenadenfest <a href=\'https://www.promenadenfest.com/ \' class=\'linkified\'>https://www.promenadenfest.com/</a> den Bewohnern der Messestadt und Umgebung mit einem Infostand vorstellen. Hierzu werden noch Helfer gesucht.<br/>Aufbau ist ab 11:00 möglich.<br/>Der Stand sollte von 15:00 bis ca. 21:00 Uhr besetzt sein und es sollte immer jemand anwesend sein, der Deutsch kann.<br/>Wer kann helfen?</p> <p>Vielen Dank und Grüße<br/>Michael Tel. [masked]</p> ',
            visibility: 'public',
        },
    ],
};

export { mockEvents };